### ISSUE TITLE
404 when you click a search result

### ISSUE THREAD

**Issue by bioluminesceme** [patrickdaze/bulma-search-chrome#4]
When I click on one of the cards to go to the page that has what I searched for, it 404s.

> 404
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
> 
> Read the full documentation for more information about using GitHub Pages.
> 
> GitHub Status — @githubstatus

**Comment by patrickdaze** [comment]
What URL is in the address bar when you see the 404 page?

**Comment by bioluminesceme** [comment]
If I click on the first "Overview" card it's 

https://bulma.io/documentation/documentation/overview

Ah, with double /documentation

**Comment by bioluminesceme** [comment]
It looks like it's adding /documentation/pagename to whatever URL you're currently on?

If I'm on https://bulma.io/videos/ and click on the search icon, the URL becomes 

    https://bulma.io/videos/documentation/overview

**Comment by ghost** [comment]
Same problem here for the page : 
https://bulma.io/documentation/documentation/columns/options#centering-columns

**Comment by patrickdaze** [comment]
@benninkcorien and @dnymxm should be fixed now!
